Purchase Department Authorization for Odoo
smsperkasa/odoo-project pull request #245
Opened 2022-10-28 09:34 UTC by NymGeri

2022-10-28 11:53 UTC, admin-smsp approved these changes

2022-10-28 11:55 UTC, admin-smsp reviewed
error in e faktur list

2022-10-28 11:56 UTC, admin-smsp reviewed
error in e faktur list

2022-10-28 11:57 UTC, admin-smsp requested changes
error in e faktur list

2022-11-11 03:57 UTC, zainawi approved these changes

2022-11-11 04:14 UTC, admin-smsp approved these changes

2022-11-11 04:14 UTC, merged